[package]
name = "luau-lsp"
version = "0.1.0"
authors = ["Meqolo <45327591+Meqolo@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonrpc-stdio-server = "17.0.0"
jsonrpc-core = "17.0.0"